# config/setting.yaml

global:
  num_workers: 4  # Number of threads for parallel KPI evaluations

code_generation:
  enabled: true
  model: gpt-3.5-turbo
  input: input/code_generation.csv
  output: output/code_generation_results.csv
  kpis:
    functional_correctness:
      enabled: true
      inputs: ["prompt", "code"]

    maintainability:
      enabled: true
      inputs: ["code"]

    code_smells:
      enabled: true
      inputs: ["code"]

    hallucination:
      enabled: true
      inputs: ["prompt", "code"]

    technical_bias:
      enabled: true
      inputs: ["prompt", "code"]

    inherent_bias:
      enabled: true
      inputs: ["prompt", "code"]

    cyclomatic_complexity:
      enabled: true
      inputs: ["code"]
      threshold: 10

    cognitive_complexity:
      enabled: true
      inputs: ["code"]
      threshold: 6

# Code Enhancement Configuration
code_enhancement:
  enabled: true
  model: gpt-3.5-turbo
  input: input/code_enhancement.csv
  output: output/code_enhancement_results.csv
  kpis:
    functional_correctness:
      enabled: true
      inputs: ["original_code", "enhancement_prompt", "enhanced_code"]

    maintainability:
      enabled: true
      inputs: ["enhanced_code"]

    code_smells:
      enabled: true
      inputs: ["enhanced_code"]

    hallucination:
      enabled: true
      inputs: ["original_code", "enhancement_prompt", "enhanced_code"]

    technical_bias:
      enabled: true
      inputs: ["original_code", "enhancement_prompt", "enhanced_code"]

    inherent_bias:
      enabled: true
      inputs: ["original_code", "enhancement_prompt", "enhanced_code"]

    cyclomatic_complexity:
      enabled: true
      inputs: ["enhanced_code"]
      threshold: 10

    cognitive_complexity:
      enabled: true
      inputs: ["enhanced_code"]
      threshold: 6
